inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true

  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - Gemfile

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
