development: &defaults
  available_locales:
    - :ru
    - :en
  debug: false
  main_email: 'info@local.ru'
  native_locale: 'ru'
  s3:
    directory: 'rails_template1'
    key: '<%= ENV['S3_KEY'] || '12345' %>'
    secret: '<%= ENV['S3_SECRET'] || '12345' %>'
  secondary_email: ''

test:
  <<: *defaults

stage:
  <<: *defaults

production:
  <<: *defaults
